package:
   name: cfitsio
   version: "3.410"

source:
  fn: cfitsio_latest.tar.gz
  url: ftp://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio_latest.tar.gz

build:
  number: 0

requirements:

 build:

 run:

about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/
  license: GPL2
